# Generated by Django 4.2.1 on 2023-05-12 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogueColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1', models.CharField(max_length=30)),
                ('color_2', models.CharField(max_length=30)),
                ('color_3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContrastColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1', models.CharField(max_length=30)),
                ('color_2', models.CharField(max_length=30)),
                ('color_3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=100)),
                ('analogue_palette_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemsImages.analoguecolors')),
                ('contrast_palette_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemsImages.contrastcolors')),
            ],
        ),
    ]
