# Generated by Django 4.2.1 on 2023-05-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsImages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image_name',
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='items',
            name='rmbg_image',
            field=models.ImageField(default=None, upload_to='images_rmbg'),
        ),
    ]
