# Generated by Django 4.2.1 on 2023-05-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsImages', '0002_remove_items_image_name_items_image_items_rmbg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='rmbg_image',
            field=models.ImageField(blank=True, default=None, upload_to='images_rmbg'),
        ),
    ]
