# Generated by Django 4.2.1 on 2023-05-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemsImages', '0003_alter_items_rmbg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='analogue_palette_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='itemsImages.analoguecolors'),
        ),
        migrations.AlterField(
            model_name='items',
            name='contrast_palette_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='itemsImages.contrastcolors'),
        ),
    ]
